import type { BattleDefinition } from '../schemas/game';

const make = (battle: Omit<BattleDefinition, 'schemaVersion'>): BattleDefinition => ({ schemaVersion: 1, ...battle });
const criteria = (skill: string): [string, string, string, string] => ['אבחון הבעיה', `שימוש ב${skill}`, 'בדיקה ושיפור', 'הסבר הקשר לתוצאה'];

export const battles: BattleDefinition[] = [
  make({ battleId:'battle_01', order:1, regionId:'recruitment', title:'קריאת כיוון', villain:null, battleType:'prompt_assembly', skillLabel:'מטרה ברורה', story:'הסימולטור מחכה לפעולה, אבל לופּ קיבל רק תמונת מצב.', objective:'הכניסו את המסמך למערכת.', instruction:'בחרו מטרה מדויקת ושלחו שוב.', concept:'מטרה היא הפעולה שאנחנו מבקשים. למשל: ציירו, תרגמו או סרקו.', promptFrame:'[המסמך מונח על השולחן] — לופּ צריך...', choices:[{id:'check',label:'בדוק את המסמך',outcome:'לופּ בדק את המסמך, אך הוא עדיין על השולחן.'},{id:'save',label:'שמור את המסמך',outcome:'המסמך שמור בקופסה, אך הסימולטור עדיין ריק.'},{id:'scan',label:'סרוק את המסמך'}], correctChoiceIds:['scan'], successMessage:'המסמך נסרק! המערכת הופעלה.', partialMessage:'לופּ ביצע בדיוק את הפעולה שביקשתם. בחרו פעולה שמכניסה את המסמך למחשב.', criteria:['התאמה למשימה','בחירת מטרה מדויקת','שיפור ממוקד','דיוק הפעולה'], estimatedSeconds:90, unlockPower:'goal' }),
  make({ battleId:'battle_02', order:2, regionId:'fog_district', title:'למי זה מיועד?', villain:'מר בערך', battleType:'fault_scan', skillLabel:'הקשר', story:'מר בערך מחק את הקהל מהזמנת הציוד.', objective:'התאימו ציוד לסדנת האמנות.', instruction:'מצאו למי מיועד הציוד והשלימו את ההקשר.', concept:'הקשר הוא מידע שעוזר להבין למי, איפה או למה.', promptFrame:'הזמן ציוד לסדנת האמנות עבור [חסר]', choices:[{id:'maintenance',label:'צוות חידוש הקירות',outcome:'לופּ הביא רולרים וכיסויי רצפה — ציוד לקירות, לא לסדנה.'},{id:'office',label:'צוות ארגון המשרד',outcome:'לופּ הביא תיקיות ולוחות תכנון — בדקו מי מגיע לסדנה.'},{id:'children',label:'ילדי הרובע'}], correctChoiceIds:['children'], successMessage:'כשהקהל ברור, לופּ מתאים את התוצאה.', partialMessage:'הציוד עדיין לא מתאים. חסר לנו לדעת מי ישתמש בו.', criteria:criteria('הקשר'), estimatedSeconds:90, unlockPower:'context' }),
  make({ battleId:'battle_03', order:3, regionId:'fog_district', title:'היכן אנחנו?', villain:'מר בערך', battleType:'power_selection', skillLabel:'מקום וזמן', story:'מר בערך מחק את המקום והזמן מבקשת התאורה.', objective:'האירו את מפת הסיור בחוץ בערב.', instruction:'בחרו הקשר שמתאים לסביבה.', concept:'הקשר יכול להסביר למי, איפה ומתי.', promptFrame:'הפעל תאורה עבור הסיור [חסר]', choices:[{id:'morning',label:'בתוך חדר בבוקר',outcome:'אור החדר שוטף את המפה ואינו מתאים לסיור.'},{id:'stage',label:'באולם חשוך, להצגה',outcome:'זרקור במה מאיר רק פינה אחת של המפה.'},{id:'evening',label:'בחוץ בערב, לקריאת מפות'}], correctChoiceIds:['evening'], successMessage:'מקום וזמן עזרו ללופּ להתאים את התאורה.', partialMessage:'חסרים המקום והזמן שבהם התאורה צריכה לפעול.', criteria:criteria('הקשר'), estimatedSeconds:90 }),
  make({ battleId:'battle_04', order:4, regionId:'fog_district', title:'לא בערך, בדיוק', villain:'מר בערך', battleType:'fault_repair', skillLabel:'מטרה', story:'לופּ עשה משהו כיפי, אבל לא התחילה פעילות.', objective:'ארגנו פעילות היכרות קצרה.', instruction:'החליפו את המטרה העמומה במשימה ברורה.', concept:'מטרה ברורה אומרת מה לבצע ומה צריך לקרות.', promptFrame:'תעשה משהו כיף עם הסוכנים החדשים במפגש.', choices:[{id:'music',label:'הפעל מוזיקת רקע',outcome:'המוזיקה פועלת, אבל עדיין אין פעילות היכרות.'},{id:'surprise',label:'הכן הפתעה לקבוצה',outcome:'הוכנה הפתעה, אבל לא הוגדרה פעילות.'},{id:'game',label:'ארגן משחק היכרות של חמש דקות'}], correctChoiceIds:['game'], successMessage:'מטרה ברורה אמרה ללופּ מה לארגן וכמה זמן.', partialMessage:'הפרומפט עדיין לא מגדיר משחק משותף.', criteria:criteria('מטרה'), estimatedSeconds:90 }),
  make({ battleId:'battle_05', order:5, regionId:'fog_district', title:'שפה אחת', villain:'מר בערך', battleType:'power_selection', skillLabel:'פורמט', story:'לופּ הציג את כל התפריט כפסקה אחת צפופה.', objective:'הציגו שלוש מנות כך שקל למצוא כל אחת.', instruction:'בחרו תצוגה ברורה לתפריט.', concept:'פורמט הוא המבנה שבו רוצים לקבל את התוצאה.', choices:[{id:'paragraph',label:'כפסקה אחת',outcome:'כל המנות קיימות, אבל קשה לסרוק אותן.'},{id:'summary',label:'כסיכום קצר',outcome:'לופּ הציג רק: שלוש אפשרויות זמינות.'},{id:'bullets',label:'כרשימת נקודות'}], correctChoiceIds:['bullets'], successMessage:'פורמט מתאים הופך מידע לקל למציאה.', partialMessage:'אנחנו צריכים לראות כל אפשרות בנפרד.', criteria:criteria('פורמט'), estimatedSeconds:90, unlockPower:'format' }),
  make({ battleId:'battle_06', order:6, regionId:'fog_district', title:'השוואת צורות', villain:'מר בערך', battleType:'robot_test', skillLabel:'פורמט שימושי', story:'לופּ הציג את אותו לוח בשתי צורות.', objective:'מצאו במהירות איזה צוות נמצא בכל שעה.', instruction:'בחרו את הפורמט השימושי להשוואה.', concept:'פורמט טוב מתאים למה שצריך לבדוק.', choices:[{id:'paragraph',label:'פסקה רציפה',detail:'בוקר צוות המפה, צהריים צוות הקשר, ערב צוות הציוד',outcome:'כל הנתונים נכונים, אבל קשה למצוא צוות לפי שעה.'},{id:'table',label:'טבלה',detail:'שורות נפרדות לזמן ולצוות'}], correctChoiceIds:['table'], successMessage:'הטבלה מסדרת את הנתונים להשוואה.', partialMessage:'חפשו מסך שמפריד בין זמן לצוות.', criteria:criteria('פורמט'), estimatedSeconds:90 }),
  make({ battleId:'battle_07', order:7, regionId:'fog_district', title:'שילוב עוטף', villain:'מר בערך', battleType:'combo', skillLabel:'מטרה, הקשר ופורמט', story:'מר בערך ערבב את הוראות האירוע.', objective:'ארגנו את עמדות ההשקה לתושבי הרובע.', instruction:'בחרו מטרה, הקשר ופורמט.', concept:'פרומפט שימושי מחבר פעולה, קהל וצורת תוצאה.', choices:[{id:'goal_bad',label:'הדפס פוסטרים לאירוע',outcome:'הפוסטרים מוכנים, אבל העמדות אינן מאורגנות.'},{id:'goal',label:'ארגן את עמדות ההשקה'},{id:'context_bad',label:'עבור צוות התחזוקה',outcome:'העמדות מסודרות לקהל אחר.'},{id:'context',label:'עבור תושבי הרובע'},{id:'format_bad',label:'כפסקה אחת על כרזה',outcome:'התכנית נכונה, אבל קשה לקרוא אותה בכיכר.'},{id:'format',label:'כטבלה גדולה על לוח הכיכר'}], correctChoiceIds:['goal','context','format'], successMessage:'רובע הערפל חזר להיות ברור.', partialMessage:'תקנו רכיב אחד; החלקים הנכונים נשמרים.', criteria:['מטרה','הקשר','פורמט','איטרציה'], estimatedSeconds:135, workshopVisit:1 }),
  make({ battleId:'battle_08', order:8, regionId:'no_limits_factory', title:'כמה זה מספיק', villain:'עוד־ועוד', battleType:'power_selection', skillLabel:'אילוץ כמות', story:'עוד־ועוד מחק את נקודת העצירה מהמסוע.', objective:'ייצרו כמות מדויקת של תיבות.', instruction:'בחרו גבול שאפשר לספור מראש.', concept:'אילוץ הוא גבול שמצמצם את האפשרויות.', promptFrame:'ייצר תיבות אחסון חדשות [חסר]', choices:[{id:'many',label:'הרבה תיבות',outcome:'״הרבה״ אינו מספר. לופּ לא יודע מתי לעצור.'},{id:'full',label:'עד שאזור האיסוף יתמלא',outcome:'המסוע עצר רק כשהאזור כבר התמלא.'},{id:'five',label:'בדיוק חמש תיבות'}], correctChoiceIds:['five'], successMessage:'מספר מדויק נתן ללופּ נקודת עצירה.', partialMessage:'חסר גבול מדיד שאפשר לבדוק מראש.', criteria:criteria('אילוץ'), estimatedSeconds:90, unlockPower:'constraint' }),
  make({ battleId:'battle_09', order:9, regionId:'no_limits_factory', title:'נימוסים במפעל', villain:'עוד־ועוד', battleType:'fault_scan', skillLabel:'אילוץ טון', story:'לופּ כתב אזהרה דרמטית כי הטון נשאר פתוח.', objective:'כתבו אזהרה ברורה ומכבדת.', instruction:'הוסיפו את אילוץ הטון החסר.', concept:'אילוץ טון אומר ל־AI איך לנסח: רגוע, רשמי או ידידותי.', choices:[{id:'joke',label:'בטון מתבדח',outcome:'החרוז המשחקי הסתיר את ההנחיה.'},{id:'drama',label:'בטון דרמטי מאוד',outcome:'הדרמה הסתירה מה צריך לעשות.'},{id:'calm',label:'בשפה רגועה ומכבדת'}], correctChoiceIds:['calm'], successMessage:'זהירות: רצפה רטובה. עברו במסלול המסומן.', partialMessage:'בחרו טון שנשאר ברור, רציני ומכבד.', criteria:criteria('אילוץ טון'), estimatedSeconds:90 }),
  make({ battleId:'battle_10', order:10, regionId:'no_limits_factory', title:'הראו לי איך', villain:'עוד־ועוד', battleType:'power_selection', skillLabel:'דוגמה', story:'לופּ קיבל תיאור כללי ויצר כתם במקום סמל.', objective:'עצבו סמל מתאים למדי הסוכנות.', instruction:'בחרו דוגמה שממחישה את הסגנון.', concept:'דוגמה רלוונטית מראה למה התכוונו.', choices:[{id:'colors',label:'בצבעים כחול וסגול',outcome:'הצבעים נכונים, אך המבנה עדיין לא ברור.'},{id:'arrow',label:'כמו שלט ההכוונה במפעל',outcome:'לופּ חיקה את החץ במקום את סמל הסוכנות.'},{id:'approved',label:'כמו דוגמת סמל הסוכנות המאושרת'}], correctChoiceIds:['approved'], successMessage:'הדוגמה הרלוונטית הבהירה את הסגנון.', partialMessage:'בחרו דוגמה ששייכת למדי הסוכנות.', criteria:criteria('דוגמה'), estimatedSeconds:90, unlockPower:'example' }),
  make({ battleId:'battle_11', order:11, regionId:'no_limits_factory', title:'רק לא זה', villain:'עוד־ועוד', battleType:'prompt_assembly', skillLabel:'דוגמה מנוגדת', story:'עוד־ועוד מילא את שולחן הישיבות בצעצועים.', objective:'הכינו חדר ישיבות מסודר.', instruction:'בחרו מטרה ודוגמת ״לא כך״.', concept:'דוגמה מנוגדת מראה תוצאה שלא רוצים לקבל.', choices:[{id:'goal_bad',label:'מלא את החדר בהפתעות צבעוניות',outcome:'לופּ ביצע את המטרה, אך החדר לא מוכן לפגישה.'},{id:'goal',label:'קשט את חדר הישיבות לפגישה בסגנון הסוכנות'},{id:'counter_bad',label:'אל תעשה עיצוב לא יפה',outcome:'״לא יפה״ הוא שיפוט כללי מדי.'},{id:'counter',label:'בלי צעצועים ובלי עומס על השולחן'}], correctChoiceIds:['goal','counter'], successMessage:'מטרה ברורה ודוגמה מנוגדת עבדו יחד.', partialMessage:'שמרו את החלק הנכון ותקנו את החלק שנותר.', criteria:criteria('דוגמה מנוגדת'), estimatedSeconds:90 }),
  make({ battleId:'battle_12', order:12, regionId:'no_limits_factory', title:'מבחן איכות', villain:'עוד־ועוד', battleType:'robot_test', skillLabel:'קריטריון הצלחה', story:'המילה ״טובה״ אפשרה גם לסוללות קצרות לעבור.', objective:'אשרו רק סוללה שעובדת יותר משעתיים.', instruction:'בחרו מבחן מדיד לפי ספר הנהלים.', concept:'קריטריון הצלחה הוא כלל שאפשר לבדוק מול תוצאה.', choices:[{id:'vague',label:'האם הסוללה טובה?',outcome:'שתי הסוללות קיבלו סימן שאלה.'},{id:'weight',label:'האם הסוללה כבדה?',outcome:'זה מדיד, אבל לא קשור לכלל.'},{id:'duration',label:'האם זמן העבודה גדול משעתיים?'}], correctChoiceIds:['duration'], successMessage:'סוללה Beta: 3 שעות — עבר. Alpha: 90 דקות — לא עבר.', partialMessage:'השתמשו באותו נתון ובאותו גבול שמופיעים במדריך.', criteria:criteria('קריטריון'), estimatedSeconds:90, unlockPower:'success_criterion' }),
  make({ battleId:'battle_13', order:13, regionId:'no_limits_factory', title:'פס הייצור', villain:'עוד־ועוד', battleType:'combo', skillLabel:'בקרת איכות', story:'שער הבקרה עצר אריזות שחסרים להן שלושה כלי פיקוח.', objective:'בקרו את האריזות לפני היציאה.', instruction:'בחרו אילוץ, דוגמה וקריטריון.', concept:'גבול, דוגמה ובדיקה עובדים יחד.', choices:[{id:'limit_bad',label:'קל ככל האפשר',outcome:'אין גבול שאפשר למדוד.'},{id:'limit',label:'משקל מרבי: 5 ק״ג לאריזה'},{id:'example_bad',label:'משהו יפה ומרשים',outcome:'לא ניתנה תבנית ברורה.'},{id:'example',label:'כמו אריזה תקנית א׳ המצורפת'},{id:'criterion_bad',label:'בדוק שהאריזה נראית טוב',outcome:'מראה טוב אינו מבחן אטימות.'},{id:'criterion',label:'אפס טיפות אחרי התזה של 10 שניות'}], correctChoiceIds:['limit','example','criterion'], successMessage:'מפעל בלי גבולות חזר לעבוד תחת בקרה.', partialMessage:'בחרו כרטיס שאפשר ליישם או לבדוק בבירור.', criteria:['אילוץ 5 ק״ג','דוגמה תקנית','בדיקת אטימות','איטרציה'], estimatedSeconds:135, workshopVisit:2 }),
  make({ battleId:'battle_14', order:14, regionId:'command_maze', title:'לפי הסדר', villain:'תסבוכת', battleType:'prompt_assembly', skillLabel:'סדר פעולות', story:'תסבוכת ערבבה את שלבי האריזה.', objective:'הכניסו מכתב, סגרו והעבירו למסוע.', instruction:'בחרו את שלושת השלבים לפי הסדר.', concept:'סדר ברור מציין איזו פעולה קודמת לפעולה שתלויה בה.', choices:[{id:'insert',label:'1. הכניסו את מכתב הברכה'},{id:'close',label:'2. סגרו את הקופסה'},{id:'move',label:'3. העבירו למסוע'},{id:'paint',label:'צבעו את המדף',outcome:'המדף נצבע, אך הקופסה אינה מוכנה.'}], correctChoiceIds:['insert','close','move'], successMessage:'המכתב בפנים, הקופסה סגורה והיא עברה למסוע.', partialMessage:'בחרו בפעולה שהתנאים שלה כבר מוכנים.', criteria:criteria('סדר'), estimatedSeconds:105, unlockPower:'structure_order' }),
  make({ battleId:'battle_15', order:15, regionId:'command_maze', title:'הפרדת כוחות', villain:'תסבוכת', battleType:'fault_scan', skillLabel:'הוראות ונתונים', story:'תסבוכת חיברה את ההוראה והיומן לבלוק אחד.', objective:'סכמו רק את יומן המסע.', instruction:'בחרו סימון שמקיף את היומן.', concept:'הוראה אומרת מה לעשות; נתונים הם החומר שעליו עובדים.', choices:[{id:'please',label:'הוסיפו ״בבקשה״',outcome:'זו מילת נימוס, לא גבול לנתונים.'},{id:'start',label:'סמנו רק ״תחילת היומן״',outcome:'תחילת היומן ברורה, אבל הסוף עדיין פתוח.'},{id:'bounds',label:'״תחילת היומן״ וגם ״סוף היומן״'}], correctChoiceIds:['bounds'], successMessage:'לופּ סיכם רק את הטקסט שבין תחילת היומן לסופו.', partialMessage:'בחרו סימון שמגדיר גם התחלה וגם סוף.', criteria:criteria('הפרדה'), estimatedSeconds:105, unlockPower:'instruction_data_separation' }),
  make({ battleId:'battle_16', order:16, regionId:'command_maze', title:'סתירה פנימית', villain:'תסבוכת', battleType:'fault_repair', skillLabel:'סתירות וניסוח חיובי', story:'שתי דרישות מתנגשות גרמו לטקסט להיחתך.', objective:'התאימו את הטקסט לכרטיס קטן.', instruction:'החליפו את הסתירה בכלל אחד.', concept:'סתירה נוצרת כששתי דרישות לא יכולות להתקיים יחד.', choices:[{id:'vague',label:'כתב גדול, אבל לא גדול מדי',outcome:'הגודל עדיין סובייקטיבי.'},{id:'negative',label:'אל תשתמשו בכתב ענק או זעיר',outcome:'נשאר טווח פתוח ללא יעד.'},{id:'medium',label:'כתב בינוני וברור'}], correctChoiceIds:['medium'], successMessage:'כל הטקסט נכנס לכרטיס ונשאר ברור.', partialMessage:'אמרו ישירות באיזה גודל כן להשתמש.', criteria:criteria('ניסוח חיובי'), estimatedSeconds:105 }),
  make({ battleId:'battle_17', order:17, regionId:'command_maze', title:'צעד אחר צעד', villain:'תסבוכת', battleType:'robot_test', skillLabel:'איטרציה מבוקרת', story:'תסבוכת שינתה כמה חלקים יחד. קשה לדעת מה עבד.', objective:'בדקו שינוי אחד לעומת גרסת הבסיס.', instruction:'בחרו ניסוי שמבודד שינוי אחד.', concept:'באבחון, שינוי אחד בכל בדיקה מאפשר השוואה ברורה.', choices:[{id:'none',label:'גרסת הבסיס ללא שינוי',outcome:'לא בדקנו את שיטת המיון החדשה.'},{id:'many',label:'שנו צבע, מגירות ומדבקות',outcome:'כמה דברים השתנו יחד, ולכן לא נדע מה השפיע.'},{id:'sort',label:'שנו רק את שיטת המיון לצבע'}], correctChoiceIds:['sort'], successMessage:'רק שיטת המיון השתנתה — עכשיו אפשר להסביר את השיפור.', partialMessage:'שמרו את החלקים שעבדו ושנו רק את שיטת המיון.', criteria:criteria('איטרציה'), estimatedSeconds:105, unlockPower:'iteration' }),
  make({ battleId:'battle_18', order:18, regionId:'command_maze', title:'יציאה מהמבוך', villain:'תסבוכת', battleType:'combo', skillLabel:'מבנה, סתירות ואיטרציה', story:'ההוראות מפוזרות וסותרות, והקובץ מגיע למגש שגוי.', objective:'סדרו את מסלול הקובץ למגש האישור.', instruction:'בחרו סדר, כלל ושינוי ממוקד.', concept:'מבנה, כלל עקבי ושינוי ממוקד מאפשרים תיקון ברור.', choices:[{id:'order',label:'פתחו → בדקו חותמת → העבירו'},{id:'order_bad',label:'העבירו → בדקו → פתחו',outcome:'הקובץ הועבר לפני שנבדק.'},{id:'rule',label:'הסתמכו על חותמת האישור'},{id:'rule_bad',label:'בדקו וגם התעלמו מהחותמת',outcome:'ההוראות עדיין סותרות.'},{id:'change',label:'שנו רק את היעד למגש אישור'},{id:'change_bad',label:'שנו שוב את כל השלבים',outcome:'שינוי כפול מסתיר מה השפיע.'}], correctChoiceIds:['order','rule','change'], successMessage:'יצאתם מהמבוך. מגדל הוודאות נפתח.', partialMessage:'שמרו את החלקים הנכונים ותקנו רק את הבעיה שנותרה.', criteria:['מבנה','פתרון סתירה','שינוי ממוקד','הסבר סיבתי'], estimatedSeconds:135, workshopVisit:3 }),
  make({ battleId:'battle_19', order:19, regionId:'certainty_tower', title:'אותו הדבר בדיוק?', villain:'ד״ר ודאות', battleType:'robot_test', skillLabel:'הסתברות', story:'אותה בקשה יצרה שתי תוצאות שונות.', objective:'בחרו תוצאה שעומדת בקריטריון.', instruction:'בדקו כל תוצאה מול הכלל.', concept:'AI עשוי להציע תוצאה שונה גם כשהבקשה זהה.', promptFrame:'המדים חייבים לכלול סמל סוכנות ברור.', choices:[{id:'silver',label:'מדים כסופים ללא סמל',outcome:'התוצאה נראית טובה, אבל חסר בה הסמל הנדרש.'},{id:'blue',label:'מדים כחולים עם סמל סוכנות'}], correctChoiceIds:['blue'], successMessage:'בדקתם את התוצאה מול הקריטריון, לא לפי המראה.', partialMessage:'שונות אינה מוכיחה איכות. חפשו את הסמל הנדרש.', criteria:criteria('בדיקה'), estimatedSeconds:90, unlockPower:'probability' }),
  make({ battleId:'battle_20', order:20, regionId:'certainty_tower', title:'מי אמר?', villain:'ד״ר ודאות', battleType:'responsibility_shield', skillLabel:'אימות', story:'הלוח נראה רשמי, אבל שעת התדריך לא נבדקה.', objective:'אמתו את השעה לפני האישור.', instruction:'בחרו מקור נפרד ומתאים.', concept:'אימות הוא השוואה למקור נפרד ומתאים.', promptFrame:'תשובת AI: 10:00 · מדריך מאושר: 08:00', choices:[{id:'looks',label:'אשרו כי הלוח נראה רשמי',outcome:'עיצוב רשמי אינו ראיה.'},{id:'ask',label:'שאלו שוב את אותו AI',outcome:'תשובה נוספת מאותו מקור אינה אימות עצמאי.'},{id:'guide',label:'השוו למדריך המשימה המאושר'}], correctChoiceIds:['guide'], successMessage:'השעה המאומתת היא 08:00.', partialMessage:'השתמשו במקור שנוצר בנפרד מהתשובה.', criteria:criteria('אימות'), estimatedSeconds:105, unlockPower:'verification' }),
  make({ battleId:'battle_21', order:21, regionId:'certainty_tower', title:'סודות רשת', villain:'ד״ר ודאות', battleType:'fault_scan', skillLabel:'פרטיות', story:'מגן הפרטיות עצר פרטים שאינם נחוצים לברכה.', objective:'נקו את הטיוטה בלי למחוק הקשר שימושי.', instruction:'בחרו את שני הפרטים שיש להסיר.', concept:'לפני שיתוף עם AI, מסירים מידע אישי שאינו נחוץ.', choices:[{id:'name',label:'[שם מלא]'},{id:'address',label:'[כתובת בית]'},{id:'team',label:'צוות החילוץ',outcome:'זהו ההקשר הדרוש לברכה.'},{id:'length',label:'שני משפטים',outcome:'זהו אילוץ שימושי, לא מידע אישי.'}], correctChoiceIds:['name','address'], successMessage:'הברכה נשארה שימושית — בלי פרטים מזהים.', partialMessage:'חפשו פרטים שמזהים אדם ואינם נחוצים למשימה.', criteria:['הסרת שם','הסרת כתובת','שמירת הקשר','הסבר פרטיות'], estimatedSeconds:105, unlockPower:'privacy' }),
  make({ battleId:'battle_22', order:22, regionId:'certainty_tower', title:'שומר הסף', villain:'ד״ר ודאות', battleType:'combo', skillLabel:'אחריות', story:'דוח המשימה כולל הצעה לא מאומתת ופרט אישי.', objective:'נקו ואמתו את הדוח לפני האישור.', instruction:'שמרו מידע נתמך והסירו את השאר.', concept:'תוצר AI הוא הצעה לבדיקה, לא הוכחה.', choices:[{id:'keep_scan',label:'שמרו: סריקת אזור'},{id:'remove_lasers',label:'הסירו: מופע לייזרים'},{id:'remove_phone',label:'הסירו: [מספר טלפון]'},{id:'remove_scan',label:'הסירו גם את סריקת האזור',outcome:'סריקת האזור דווקא נתמכת בנוהל.'},{id:'keep_all',label:'השאירו הכול כי זה כתוב בביטחון',outcome:'ניסוח בטוח אינו הוכחה.'}], correctChoiceIds:['keep_scan','remove_lasers','remove_phone'], successMessage:'נשאר רק מידע מאומת ולא אישי.', partialMessage:'פרטיות קודמת; אחריה בודקים כל טענה מול המקור.', criteria:['פרטיות','אימות','הבנת הסתברות','בדיקה מחדש'], estimatedSeconds:135, workshopVisit:4, unlockPower:'responsibility' }),
  make({ battleId:'battle_23', order:23, regionId:'finale', title:'שחזור התכנית', villain:'המשבש', battleType:'combo', skillLabel:'שילוב מלא', story:'המשבש מחק את לוח הבקרה. שחזרו אותו בעזרת המדריך.', objective:'כתבו ללופּ בקשה בטוחה ומלאה.', instruction:'כתבו בקשה שמשחזרת את התכנית.', concept:'מטרה, הקשר, אילוץ, פורמט ובדיקה יוצרים תהליך אחראי.', choices:[], correctChoiceIds:[], successMessage:'לוח התכנית שוחזר בהצלחה!', partialMessage:'תקנו רק את הרכיב שסומן ושמרו את השאר.', criteria:['התאמה למשימה','רכיבי פרומפט','בדיקה ושיפור','אחריות ובטיחות'], estimatedSeconds:165 }),
];

export const battleById = Object.fromEntries(battles.map((battle) => [battle.battleId, battle])) as Record<string, BattleDefinition>;

export interface SkillCatalogEntry { powerId: string; label: string; battleOrder: number }
export const skillCatalog: SkillCatalogEntry[] = battles
  .filter((battle): battle is BattleDefinition & { unlockPower: string } => Boolean(battle.unlockPower))
  .map((battle) => ({ powerId: battle.unlockPower, label: battle.skillLabel, battleOrder: battle.order }));

export function validateBattleRegistry(registry = battles): string[] {
  const errors: string[] = [];
  if (registry.length !== 23) errors.push('ה־registry חייב להכיל בדיוק 23 קרבות');
  registry.forEach((battle, index) => {
    if (battle.order !== index + 1) errors.push(`סדר לא תקין בקרב ${battle.battleId}`);
    if (battle.criteria.length !== 4) errors.push(`חסרים ארבעה קריטריונים בקרב ${battle.battleId}`);
    if (battle.order < 23 && battle.correctChoiceIds.length === 0) errors.push(`אין פתרון לקרב ${battle.battleId}`);
  });
  if (new Set(registry.map((battle) => battle.battleId)).size !== registry.length) errors.push('מזהה קרב כפול');
  return errors;
}
