import type { BattleDefinition } from '../schemas/game';

const make = (battle: Omit<BattleDefinition, 'schemaVersion'>): BattleDefinition => ({ schemaVersion: 1, ...battle });
const criteria = (skill: string): [string, string, string, string] => ['אבחון הבעיה', `שימוש ב${skill}`, 'בדיקה ושיפור', 'הסבר הקשר לתוצאה'];

export const battles: BattleDefinition[] = [
  make({ battleId:'battle_01', order:1, regionId:'recruitment', title:'קריאת כיוון', villain:null, battleType:'prompt_assembly', skillLabel:'מטרה ברורה', story:'הסימולטור מחכה לפעולה, אבל לופּ קיבל רק תמונת מצב.', objective:'הכניסו את המסמך למערכת.', instruction:'בחרו מטרה מדויקת ושלחו שוב.', concept:'מטרה היא הפעולה שאנחנו מבקשים. למשל: ציירו, תרגמו או סרקו.', promptFrame:'[המסמך מונח על השולחן] — לופּ צריך...', choices:[{id:'check',label:'בדוק את המסמך',outcome:'לופּ בדק את המסמך, אך הוא עדיין על השולחן. "בדוק" הוא פועל בקרה — הוא לא מזין מידע למערכת. המטרה עדיין לא מדויקת.'},{id:'save',label:'שמור את המסמך',outcome:'המסמך שמור בקופסה, אך הסימולטור עדיין ריק. "שמור" מגן על הנייר במקום להעביר אותו למערכת — זו עדיין לא הפעולה הדרושה.'},{id:'scan',label:'סרוק את המסמך'}], correctChoiceIds:['scan'], successMessage:'המסמך נסרק! המערכת הופעלה.', partialMessage:'לופּ ביצע בדיוק את הפעולה שביקשתם. בחרו פעולה שמכניסה את המסמך למחשב.', successExplanation:'סריקה היא הפעולה שמזינה את המסמך למחשב — בדיוק המטרה שנדרשה. פרומפט טוב פותח בפועל פעולה ברור, כדי שה־AI ידע מה לבצע ולא ינחש. למשל: "תעזור עם השיעור" מעורפל; "סכם את הפרק" הוא מטרה ברורה.', criteria:['התאמה למשימה','בחירת מטרה מדויקת','שיפור ממוקד','דיוק הפעולה'], estimatedSeconds:90, unlockPower:'goal' }),
  make({ battleId:'battle_02', order:2, regionId:'fog_district', title:'למי זה מיועד?', villain:'מר בערך', battleType:'fault_scan', skillLabel:'הקשר', story:'מר בערך מחק את הקהל מהזמנת הציוד.', objective:'התאימו ציוד לסדנת האמנות.', instruction:'מצאו למי מיועד הציוד והשלימו את ההקשר.', concept:'הקשר הוא מידע שעוזר להבין למי, איפה או למה.', promptFrame:'הזמן ציוד לסדנת האמנות עבור [חסר]', choices:[{id:'maintenance',label:'צוות חידוש הקירות',outcome:'לופּ הביא רולרים וכיסויי רצפה — ציוד לקירות, לא לסדנה. חסר הקשר: מי בדיוק משתמש בציוד.'},{id:'office',label:'צוות ארגון המשרד',outcome:'לופּ הביא תיקיות ולוחות תכנון — בדקו מי מגיע לסדנה. עדיין חסר ההקשר: מיהו הקהל האמיתי.'},{id:'children',label:'ילדי הרובע'}], correctChoiceIds:['children'], successMessage:'כשהקהל ברור, לופּ מתאים את התוצאה.', partialMessage:'הציוד עדיין לא מתאים. חסר לנו לדעת מי ישתמש בו.', successExplanation:'כשציינתם שהציוד מיועד לילדי הרובע, לופּ ידע בדיוק מה להביא. הקשר אומר ל־AI "למי" זה מיועד — בלעדיו הוא בוחר ברירת מחדל שרירותית. גם מחוץ למשחק, ציון הקהל משנה לגמרי את התשובה שמתקבלת.', criteria:criteria('הקשר'), estimatedSeconds:90, unlockPower:'context' }),
  make({ battleId:'battle_03', order:3, regionId:'fog_district', title:'היכן אנחנו?', villain:'מר בערך', battleType:'power_selection', skillLabel:'מקום וזמן', story:'מר בערך מחק את המקום והזמן מבקשת התאורה.', objective:'האירו את מפת הסיור בחוץ בערב.', instruction:'בחרו הקשר שמתאים לסביבה.', concept:'הקשר יכול להסביר למי, איפה ומתי.', promptFrame:'הפעל תאורה עבור הסיור [חסר]', choices:[{id:'morning',label:'בתוך חדר בבוקר',outcome:'אור החדר שוטף את המפה ואינו מתאים לסיור. חסר ההקשר הנכון: מקום וזמן הפעילות.'},{id:'stage',label:'באולם חשוך, להצגה',outcome:'זרקור במה מאיר רק פינה אחת של המפה. גם כאן ההקשר — מקום וזמן — לא תואם לסיור בחוץ.'},{id:'evening',label:'בחוץ בערב, לקריאת מפות'}], correctChoiceIds:['evening'], successMessage:'מקום וזמן עזרו ללופּ להתאים את התאורה.', partialMessage:'חסרים המקום והזמן שבהם התאורה צריכה לפעול.', successExplanation:'בחוץ בערב צריך תאורה חזקה לקריאת מפה בחושך — זה מה שהבחירה הזו מספקת. מקום וזמן הם חלק מההקשר: הם אומרים ל־AI באילו תנאים התוצאה צריכה לפעול בפועל.', criteria:criteria('הקשר'), estimatedSeconds:90 }),
  make({ battleId:'battle_04', order:4, regionId:'fog_district', title:'לא בערך, בדיוק', villain:'מר בערך', battleType:'fault_repair', skillLabel:'מטרה', story:'לופּ עשה משהו כיפי, אבל לא התחילה פעילות.', objective:'ארגנו פעילות היכרות קצרה.', instruction:'החליפו את המטרה העמומה במשימה ברורה.', concept:'מטרה ברורה אומרת מה לבצע ומה צריך לקרות.', promptFrame:'תעשה משהו כיף עם הסוכנים החדשים במפגש.', choices:[{id:'music',label:'הפעל מוזיקת רקע',outcome:'המוזיקה פועלת, אבל עדיין אין פעילות היכרות. המטרה עדיין לא מגדירה איזו פעילות לבצע.'},{id:'surprise',label:'הכן הפתעה לקבוצה',outcome:'הוכנה הפתעה, אבל לא הוגדרה פעילות. גם כאן חסרה מטרה שמתארת פעולה קונקרטית.'},{id:'game',label:'ארגן משחק היכרות של חמש דקות'}], correctChoiceIds:['game'], successMessage:'מטרה ברורה אמרה ללופּ מה לארגן וכמה זמן.', partialMessage:'הפרומפט עדיין לא מגדיר משחק משותף.', successExplanation:'"ארגן משחק היכרות של חמש דקות" הוא פועל פעולה קונקרטי שאומר בדיוק מה לבנות וכמה זמן. מטרה ברורה מחליפה ניסוח מעורפל כמו "תעשה משהו כיף" בפעולה שאפשר לבצע ולבדוק.', criteria:criteria('מטרה'), estimatedSeconds:90 }),
  make({ battleId:'battle_05', order:5, regionId:'fog_district', title:'שפה אחת', villain:'מר בערך', battleType:'power_selection', skillLabel:'פורמט', story:'לופּ הציג את כל התפריט כפסקה אחת צפופה.', objective:'הציגו שלוש מנות כך שקל למצוא כל אחת.', instruction:'בחרו תצוגה ברורה לתפריט.', concept:'פורמט הוא המבנה שבו רוצים לקבל את התוצאה.', choices:[{id:'paragraph',label:'כפסקה אחת',outcome:'כל המנות קיימות, אבל קשה לסרוק אותן. הפורמט (פסקה) לא מתאים למידע שצריך להשוות.'},{id:'summary',label:'כסיכום קצר',outcome:'לופּ הציג רק: שלוש אפשרויות זמינות. הפורמט הזה תמציתי מדי — הוא מסתיר את הפרטים שביקשתם.'},{id:'bullets',label:'כרשימת נקודות'}], correctChoiceIds:['bullets'], successMessage:'פורמט מתאים הופך מידע לקל למציאה.', partialMessage:'אנחנו צריכים לראות כל אפשרות בנפרד.', successExplanation:'רשימת נקודות מציגה כל מנה בנפרד, כך שקל לסרוק ולהשוות במבט אחד. פורמט הוא ההנחיה שאומרת ל־AI באיזו צורה להציג מידע — הבחירה הנכונה הופכת תוכן נכון לשימושי.', criteria:criteria('פורמט'), estimatedSeconds:90, unlockPower:'format' }),
  make({ battleId:'battle_06', order:6, regionId:'fog_district', title:'השוואת צורות', villain:'מר בערך', battleType:'robot_test', skillLabel:'פורמט שימושי', story:'לופּ הציג את אותו לוח בשתי צורות.', objective:'מצאו במהירות איזה צוות נמצא בכל שעה.', instruction:'בחרו את הפורמט השימושי להשוואה.', concept:'פורמט טוב מתאים למה שצריך לבדוק.', choices:[{id:'paragraph',label:'פסקה רציפה',detail:'בוקר צוות המפה, צהריים צוות הקשר, ערב צוות הציוד',outcome:'כל הנתונים נכונים, אבל קשה למצוא צוות לפי שעה. הפורמט (פסקה רציפה) לא מתאים להשוואה מהירה.'},{id:'table',label:'טבלה',detail:'שורות נפרדות לזמן ולצוות'}], correctChoiceIds:['table'], successMessage:'הטבלה מסדרת את הנתונים להשוואה.', partialMessage:'חפשו מסך שמפריד בין זמן לצוות.', successExplanation:'טבלה מפרידה זמן וצוות לשורות נפרדות, כך שאפשר למצוא מי עובד מתי בלי לקרוא הכול. כשצריך להשוות נתונים, פורמט טבלאי הוא הרכיב שקובע אם התוצאה שימושית או לא.', criteria:criteria('פורמט'), estimatedSeconds:90 }),
  make({ battleId:'battle_07', order:7, regionId:'fog_district', title:'שילוב עוטף', villain:'מר בערך', battleType:'combo', skillLabel:'מטרה, הקשר ופורמט', story:'מר בערך ערבב את הוראות האירוע.', objective:'ארגנו את עמדות ההשקה לתושבי הרובע.', instruction:'בחרו מטרה, הקשר ופורמט.', concept:'פרומפט שימושי מחבר פעולה, קהל וצורת תוצאה.', choices:[{id:'goal_bad',label:'הדפס פוסטרים לאירוע',outcome:'הפוסטרים מוכנים, אבל העמדות אינן מאורגנות. זו מטרה לא מדויקת למשימה שהוגדרה.'},{id:'goal',label:'ארגן את עמדות ההשקה'},{id:'context_bad',label:'עבור צוות התחזוקה',outcome:'העמדות מסודרות לקהל אחר. ההקשר (הקהל) לא תואם את תושבי הרובע.'},{id:'context',label:'עבור תושבי הרובע'},{id:'format_bad',label:'כפסקה אחת על כרזה',outcome:'התכנית נכונה, אבל קשה לקרוא אותה בכיכר. הפורמט (פסקה על כרזה) לא שימושי לקהל גדול.'},{id:'format',label:'כטבלה גדולה על לוח הכיכר'}], correctChoiceIds:['goal','context','format'], successMessage:'רובע הערפל חזר להיות ברור.', partialMessage:'תקנו רכיב אחד; החלקים הנכונים נשמרים.', successExplanation:'לארגן (מטרה), עבור תושבי הרובע (הקשר) וכטבלה על לוח הכיכר (פורמט) — שלושת הרכיבים יחד נותנים ללופּ הוראה מלאה שאי אפשר לפרש לא נכון. כל רכיב חסר משאיר פרצה לפרשנות שגויה.', criteria:['מטרה','הקשר','פורמט','איטרציה'], estimatedSeconds:135, workshopVisit:1 }),
  make({ battleId:'battle_08', order:8, regionId:'no_limits_factory', title:'כמה זה מספיק', villain:'עוד־ועוד', battleType:'power_selection', skillLabel:'אילוץ כמות', story:'עוד־ועוד מחק את נקודת העצירה מהמסוע.', objective:'ייצרו כמות מדויקת של תיבות.', instruction:'בחרו גבול שאפשר לספור מראש.', concept:'אילוץ הוא גבול שמצמצם את האפשרויות.', promptFrame:'ייצר תיבות אחסון חדשות [חסר]', choices:[{id:'many',label:'הרבה תיבות',outcome:'״הרבה״ אינו מספר. לופּ לא יודע מתי לעצור — האילוץ עדיין לא מדיד.'},{id:'full',label:'עד שאזור האיסוף יתמלא',outcome:'המסוע עצר רק כשהאזור כבר התמלא. האילוץ תלוי בתנאי משתנה, לא במספר קבוע.'},{id:'five',label:'בדיוק חמש תיבות'}], correctChoiceIds:['five'], successMessage:'מספר מדויק נתן ללופּ נקודת עצירה.', partialMessage:'חסר גבול מדיד שאפשר לבדוק מראש.', successExplanation:'"בדיוק חמש תיבות" הוא מספר מדויק שאפשר לספור ולבדוק — זה מה שנותן ללופּ נקודת עצירה. אילוץ מדיד מונע פרשנויות כמו "הרבה" או "עד שמתמלא", שאין להן גבול ברור.', criteria:criteria('אילוץ'), estimatedSeconds:90, unlockPower:'constraint' }),
  make({ battleId:'battle_09', order:9, regionId:'no_limits_factory', title:'נימוסים במפעל', villain:'עוד־ועוד', battleType:'fault_scan', skillLabel:'אילוץ טון', story:'לופּ כתב אזהרה דרמטית כי הטון נשאר פתוח.', objective:'כתבו אזהרה ברורה ומכבדת.', instruction:'הוסיפו את אילוץ הטון החסר.', concept:'אילוץ טון אומר ל־AI איך לנסח: רגוע, רשמי או ידידותי.', choices:[{id:'joke',label:'בטון מתבדח',outcome:'החרוז המשחקי הסתיר את ההנחיה. אילוץ הטון לא מתאים לאזהרת בטיחות.'},{id:'drama',label:'בטון דרמטי מאוד',outcome:'הדרמה הסתירה מה צריך לעשות. גם כאן אילוץ הטון לא משרת את המטרה.'},{id:'calm',label:'בשפה רגועה ומכבדת'}], correctChoiceIds:['calm'], successMessage:'זהירות: רצפה רטובה. עברו במסלול המסומן.', partialMessage:'בחרו טון שנשאר ברור, רציני ומכבד.', successExplanation:'טון רגוע ומכבד שומר את האזהרה קריאה בלי להסתיר את המסר בקישוטים. אילוץ טון אומר ל־AI באיזה סגנון לכתוב — וזה קובע אם התוצאה משרתת את המטרה או מפריעה לה.', criteria:criteria('אילוץ טון'), estimatedSeconds:90 }),
  make({ battleId:'battle_10', order:10, regionId:'no_limits_factory', title:'הראו לי איך', villain:'עוד־ועוד', battleType:'power_selection', skillLabel:'דוגמה', story:'לופּ קיבל תיאור כללי ויצר כתם במקום סמל.', objective:'עצבו סמל מתאים למדי הסוכנות.', instruction:'בחרו דוגמה שממחישה את הסגנון.', concept:'דוגמה רלוונטית מראה למה התכוונו.', choices:[{id:'colors',label:'בצבעים כחול וסגול',outcome:'הצבעים נכונים, אך המבנה עדיין לא ברור. חסרה דוגמה שממחישה צורה, לא רק צבע.'},{id:'arrow',label:'כמו שלט ההכוונה במפעל',outcome:'לופּ חיקה את החץ במקום את סמל הסוכנות. הדוגמה שנבחרה לא רלוונטית לסוג העיצוב המבוקש.'},{id:'approved',label:'כמו דוגמת סמל הסוכנות המאושרת'}], correctChoiceIds:['approved'], successMessage:'הדוגמה הרלוונטית הבהירה את הסגנון.', partialMessage:'בחרו דוגמה ששייכת למדי הסוכנות.', successExplanation:'דוגמת הסמל המאושר מראה ללופּ בדיוק את הסגנון המצופה, לא רק תיאור שאפשר לפרש בדרכים שונות. דוגמה רלוונטית ממחישה למה מתכוונים כשקשה לתאר זאת רק במילים.', criteria:criteria('דוגמה'), estimatedSeconds:90, unlockPower:'example' }),
  make({ battleId:'battle_11', order:11, regionId:'no_limits_factory', title:'רק לא זה', villain:'עוד־ועוד', battleType:'prompt_assembly', skillLabel:'דוגמה מנוגדת', story:'עוד־ועוד מילא את שולחן הישיבות בצעצועים.', objective:'הכינו חדר ישיבות מסודר.', instruction:'בחרו מטרה ודוגמת ״לא כך״.', concept:'דוגמה מנוגדת מראה תוצאה שלא רוצים לקבל.', choices:[{id:'goal_bad',label:'מלא את החדר בהפתעות צבעוניות',outcome:'לופּ ביצע את המטרה, אך החדר לא מוכן לפגישה. המטרה עדיין לא מתארת את התוצאה הרצויה.'},{id:'goal',label:'קשט את חדר הישיבות לפגישה בסגנון הסוכנות'},{id:'counter_bad',label:'אל תעשה עיצוב לא יפה',outcome:'״לא יפה״ הוא שיפוט כללי מדי — לא דוגמה מנוגדת קונקרטית.'},{id:'counter',label:'בלי צעצועים ובלי עומס על השולחן'}], correctChoiceIds:['goal','counter'], successMessage:'מטרה ברורה ודוגמה מנוגדת עבדו יחד.', partialMessage:'שמרו את החלק הנכון ותקנו את החלק שנותר.', successExplanation:'מטרה ברורה (לקשט בסגנון הסוכנות) יחד עם דוגמה מנוגדת קונקרטית (בלי צעצועים ובלי עומס) אומרות ל־AI גם מה לעשות וגם מה להימנע ממנו. דוגמה מנוגדת מצליחה רק כשהיא קונקרטית, לא שיפוט כללי כמו "לא יפה".', criteria:criteria('דוגמה מנוגדת'), estimatedSeconds:90 }),
  make({ battleId:'battle_12', order:12, regionId:'no_limits_factory', title:'מבחן איכות', villain:'עוד־ועוד', battleType:'robot_test', skillLabel:'קריטריון הצלחה', story:'המילה ״טובה״ אפשרה גם לסוללות קצרות לעבור.', objective:'אשרו רק סוללה שעובדת יותר משעתיים.', instruction:'בחרו מבחן מדיד לפי ספר הנהלים.', concept:'קריטריון הצלחה הוא כלל שאפשר לבדוק מול תוצאה.', choices:[{id:'vague',label:'האם הסוללה טובה?',outcome:'שתי הסוללות קיבלו סימן שאלה. "טובה" אינה קריטריון מדיד.'},{id:'weight',label:'האם הסוללה כבדה?',outcome:'זה מדיד, אבל לא קשור לכלל. הקריטריון חייב להתאים למה שהמדריך בודק בפועל.'},{id:'duration',label:'האם זמן העבודה גדול משעתיים?'}], correctChoiceIds:['duration'], successMessage:'סוללה בטא: 3 שעות — עברה. סוללה אלפא: 90 דקות — לא עברה.', partialMessage:'השתמשו באותו נתון ובאותו גבול שמופיעים במדריך.', successExplanation:'זמן עבודה גדול משעתיים הוא קריטריון מדיד שאפשר לבדוק מול נתון אמיתי — בדיוק מה שהנוהל דורש. קריטריון הצלחה אומר איך יודעים שהתוצאה טובה מספיק, בניגוד למילה כללית כמו "טובה".', criteria:criteria('קריטריון'), estimatedSeconds:90, unlockPower:'success_criterion' }),
  make({ battleId:'battle_13', order:13, regionId:'no_limits_factory', title:'פס הייצור', villain:'עוד־ועוד', battleType:'combo', skillLabel:'בקרת איכות', story:'שער הבקרה עצר אריזות שחסרים להן שלושה כלי פיקוח.', objective:'בקרו את האריזות לפני היציאה.', instruction:'בחרו אילוץ, דוגמה וקריטריון.', concept:'גבול, דוגמה ובדיקה עובדים יחד.', choices:[{id:'limit_bad',label:'קל ככל האפשר',outcome:'אין גבול שאפשר למדוד. "קל ככל האפשר" אינו אילוץ מדיד.'},{id:'limit',label:'משקל מרבי: 5 ק״ג לאריזה'},{id:'example_bad',label:'משהו יפה ומרשים',outcome:'לא ניתנה תבנית ברורה. "משהו יפה ומרשים" הוא תיאור, לא דוגמה קונקרטית.'},{id:'example',label:'כמו אריזה תקנית א׳ המצורפת'},{id:'criterion_bad',label:'בדוק שהאריזה נראית טוב',outcome:'מראה טוב אינו מבחן אטימות. הקריטריון לא בודק את התכונה הנדרשת.'},{id:'criterion',label:'אפס טיפות אחרי התזה של 10 שניות'}], correctChoiceIds:['limit','example','criterion'], successMessage:'מפעל בלי גבולות חזר לעבוד תחת בקרה.', partialMessage:'בחרו כרטיס שאפשר ליישם או לבדוק בבירור.', successExplanation:'משקל מרבי, דוגמת האריזה התקנית ובדיקת האטימות פועלים יחד: האילוץ קובע גבול, הדוגמה מראה צורה, והקריטריון בודק תוצאה. בלעדי אחד מהם, קל לפרש את הבקשה בדרך שלא עומדת בבקרת האיכות.', criteria:['אילוץ 5 ק״ג','דוגמה תקנית','בדיקת אטימות','איטרציה'], estimatedSeconds:135, workshopVisit:2 }),
  make({ battleId:'battle_14', order:14, regionId:'command_maze', title:'לפי הסדר', villain:'תסבוכת', battleType:'prompt_assembly', skillLabel:'סדר פעולות', story:'תסבוכת ערבבה את שלבי האריזה.', objective:'הכניסו מכתב, סגרו והעבירו למסוע.', instruction:'בחרו את שלושת השלבים לפי הסדר.', concept:'סדר ברור מציין איזו פעולה קודמת לפעולה שתלויה בה.', choices:[{id:'insert',label:'1. הכניסו את מכתב הברכה'},{id:'close',label:'2. סגרו את הקופסה'},{id:'move',label:'3. העבירו למסוע'},{id:'paint',label:'צבעו את המדף',outcome:'המדף נצבע, אך הקופסה אינה מוכנה. זו פעולה שלא שייכת כלל לשלושת השלבים הנדרשים.'}], correctChoiceIds:['insert','close','move'], successMessage:'המכתב בפנים, הקופסה סגורה והיא עברה למסוע.', partialMessage:'בחרו בפעולה שהתנאים שלה כבר מוכנים.', successExplanation:'הכנסת המכתב חייבת לקרות לפני סגירת הקופסה, ורק קופסה סגורה אפשר להעביר למסוע — זה הסדר היחיד שעובד. סדר פעולות אומר ל־AI איזו פעולה תלויה באיזו, לא רק אילו פעולות לבצע.', criteria:criteria('סדר'), estimatedSeconds:105, unlockPower:'structure_order' }),
  make({ battleId:'battle_15', order:15, regionId:'command_maze', title:'הפרדת כוחות', villain:'תסבוכת', battleType:'fault_scan', skillLabel:'הוראות ונתונים', story:'תסבוכת חיברה את ההוראה והיומן לבלוק אחד.', objective:'סכמו רק את יומן המסע.', instruction:'בחרו סימון שמקיף את היומן.', concept:'הוראה אומרת מה לעשות; נתונים הם החומר שעליו עובדים.', choices:[{id:'please',label:'הוסיפו ״בבקשה״',outcome:'זו מילת נימוס, לא גבול לנתונים. עדיין חסרה הפרדה ברורה בין ההוראה לנתונים.'},{id:'start',label:'סמנו רק ״תחילת היומן״',outcome:'תחילת היומן ברורה, אבל הסוף עדיין פתוח. ההפרדה חייבת לסמן גם היכן הנתונים מסתיימים.'},{id:'bounds',label:'״תחילת היומן״ וגם ״סוף היומן״'}], correctChoiceIds:['bounds'], successMessage:'לופּ סיכם רק את הטקסט שבין תחילת היומן לסופו.', partialMessage:'בחרו סימון שמגדיר גם התחלה וגם סוף.', successExplanation:'הסימון "תחילת היומן" ו"סוף היומן" מקיף בדיוק את הקטע לסיכום ומפריד אותו מההוראה עצמה. הפרדה בין הוראה לנתונים אומרת ל־AI היכן ההנחיה מסתיימת והחומר לעיבוד מתחיל.', criteria:criteria('הפרדה'), estimatedSeconds:105, unlockPower:'instruction_data_separation' }),
  make({ battleId:'battle_16', order:16, regionId:'command_maze', title:'סתירה פנימית', villain:'תסבוכת', battleType:'fault_repair', skillLabel:'סתירות וניסוח חיובי', story:'שתי דרישות מתנגשות גרמו לטקסט להיחתך.', objective:'התאימו את הטקסט לכרטיס קטן.', instruction:'החליפו את הסתירה בכלל אחד.', concept:'סתירה נוצרת כששתי דרישות לא יכולות להתקיים יחד.', choices:[{id:'vague',label:'כתב גדול, אבל לא גדול מדי',outcome:'הגודל עדיין סובייקטיבי. הניסוח עדיין לא נותן כלל אחד וברור.'},{id:'negative',label:'אל תשתמשו בכתב ענק או זעיר',outcome:'נשאר טווח פתוח ללא יעד. שלילה בלבד לא אומרת מה כן רוצים — הסתירה לא נפתרה.'},{id:'medium',label:'כתב בינוני וברור'}], correctChoiceIds:['medium'], successMessage:'כל הטקסט נכנס לכרטיס ונשאר ברור.', partialMessage:'אמרו ישירות באיזה גודל כן להשתמש.', successExplanation:'"כתב בינוני וברור" הוא כלל אחד וחיובי שאי אפשר לפרש בשני כיוונים סותרים. ניסוח חיובי פותר סתירה כי הוא אומר במפורש מה כן רוצים, במקום להשאיר את ה־AI לבחור בעצמו.', criteria:criteria('ניסוח חיובי'), estimatedSeconds:105 }),
  make({ battleId:'battle_17', order:17, regionId:'command_maze', title:'צעד אחר צעד', villain:'תסבוכת', battleType:'robot_test', skillLabel:'איטרציה מבוקרת', story:'תסבוכת שינתה כמה חלקים יחד. קשה לדעת מה עבד.', objective:'בדקו שינוי אחד לעומת גרסת הבסיס.', instruction:'בחרו ניסוי שמבודד שינוי אחד.', concept:'באבחון, שינוי אחד בכל בדיקה מאפשר השוואה ברורה.', choices:[{id:'none',label:'גרסת הבסיס ללא שינוי',outcome:'לא בדקנו את שיטת המיון החדשה. בלי לשנות משתנה, אי אפשר לבחון שיפור.'},{id:'many',label:'שנו צבע, מגירות ומדבקות',outcome:'כמה דברים השתנו יחד, ולכן לא נדע מה השפיע. האיטרציה לא מבודדת משתנה אחד.'},{id:'sort',label:'שנו רק את שיטת המיון לצבע'}], correctChoiceIds:['sort'], successMessage:'רק שיטת המיון השתנתה — עכשיו אפשר להסביר את השיפור.', partialMessage:'שמרו את החלקים שעבדו ושנו רק את שיטת המיון.', successExplanation:'שינוי של שיטת המיון בלבד, בלי לגעת בשאר הרכיבים, מאפשר להשוות במדויק בין הגרסה הישנה לחדשה. איטרציה מבוקרת — שינוי משתנה אחד בכל בדיקה — הופכת תיקון להסבר ברור, לא לניחוש.', criteria:criteria('איטרציה'), estimatedSeconds:105, unlockPower:'iteration' }),
  make({ battleId:'battle_18', order:18, regionId:'command_maze', title:'יציאה מהמבוך', villain:'תסבוכת', battleType:'combo', skillLabel:'מבנה, סתירות ואיטרציה', story:'ההוראות מפוזרות וסותרות, והקובץ מגיע למגש שגוי.', objective:'סדרו את מסלול הקובץ למגש האישור.', instruction:'בחרו סדר, כלל ושינוי ממוקד.', concept:'מבנה, כלל עקבי ושינוי ממוקד מאפשרים תיקון ברור.', choices:[{id:'order',label:'פתחו → בדקו חותמת → העבירו'},{id:'order_bad',label:'העבירו → בדקו → פתחו',outcome:'הקובץ הועבר לפני שנבדק. סדר הפעולות (המבנה) שגוי — תלות לא מכובדת.'},{id:'rule',label:'הסתמכו על חותמת האישור'},{id:'rule_bad',label:'בדקו וגם התעלמו מהחותמת',outcome:'ההוראות עדיין סותרות — יש עדיין שתי הנחיות שלא יכולות להתקיים יחד.'},{id:'change',label:'שנו רק את היעד למגש אישור'},{id:'change_bad',label:'שנו שוב את כל השלבים',outcome:'שינוי כפול מסתיר מה השפיע. זה לא שינוי ממוקד — קשה לדעת מה תיקן את הבעיה.'}], correctChoiceIds:['order','rule','change'], successMessage:'יצאתם מהמבוך. מגדל הוודאות נפתח.', partialMessage:'שמרו את החלקים הנכונים ותקנו רק את הבעיה שנותרה.', successExplanation:'סדר נכון, כלל אחד ועקבי ושינוי ממוקד ליעד בלבד — שלושתם יחד מוציאים את הקובץ מהמבוך בלי לבלבל את לופּ. מבנה, פתרון סתירה ואיטרציה ממוקדת מאפשרים להסביר בדיוק למה התיקון עבד.', criteria:['מבנה','פתרון סתירה','שינוי ממוקד','הסבר סיבתי'], estimatedSeconds:135, workshopVisit:3 }),
  make({ battleId:'battle_19', order:19, regionId:'certainty_tower', title:'אותו הדבר בדיוק?', villain:'ד״ר ודאות', battleType:'robot_test', skillLabel:'הסתברות', story:'אותה בקשה יצרה שתי תוצאות שונות.', objective:'בחרו תוצאה שעומדת בקריטריון.', instruction:'בדקו כל תוצאה מול הכלל.', concept:'AI עשוי להציע תוצאה שונה גם כשהבקשה זהה.', promptFrame:'המדים חייבים לכלול סמל סוכנות ברור.', choices:[{id:'silver',label:'מדים כסופים ללא סמל',outcome:'התוצאה נראית טובה, אבל חסר בה הסמל הנדרש. לא נבדקה מול קריטריון הצלחה — רק לפי מראה.'},{id:'blue',label:'מדים כחולים עם סמל סוכנות'}], correctChoiceIds:['blue'], successMessage:'בדקתם את התוצאה מול הקריטריון, לא לפי המראה.', partialMessage:'שונות אינה מוכיחה איכות. חפשו את הסמל הנדרש.', successExplanation:'מדים כחולים עם סמל סוכנות עומדים בקריטריון שנקבע מראש — סמל ברור — ולכן הם הבחירה הנכונה, גם אם התוצאה השנייה נראתה סבירה. AI יכול להחזיר תוצאות שונות לאותה בקשה, ולכן בודקים כל תוצאה מול הקריטריון, לא לפי מראה.', criteria:criteria('בדיקה'), estimatedSeconds:90, unlockPower:'probability' }),
  make({ battleId:'battle_20', order:20, regionId:'certainty_tower', title:'מי אמר?', villain:'ד״ר ודאות', battleType:'responsibility_shield', skillLabel:'אימות', story:'הלוח נראה רשמי, אבל שעת התדריך לא נבדקה.', objective:'אמתו את השעה לפני האישור.', instruction:'בחרו מקור נפרד ומתאים.', concept:'אימות הוא השוואה למקור נפרד ומתאים.', promptFrame:'תשובת AI: ⁨10:00⁩ · מדריך מאושר: ⁨08:00⁩', choices:[{id:'looks',label:'אשרו כי הלוח נראה רשמי',outcome:'עיצוב רשמי אינו ראיה. לא בוצע אימות מול מקור נפרד.'},{id:'ask',label:'שאלו שוב את אותו AI',outcome:'תשובה נוספת מאותו מקור אינה אימות עצמאי. אימות דורש מקור שונה מהתשובה עצמה.'},{id:'guide',label:'השוו למדריך המשימה המאושר'}], correctChoiceIds:['guide'], successMessage:'השעה המאומתת היא ⁨08:00⁩.', partialMessage:'השתמשו במקור שנוצר בנפרד מהתשובה.', successExplanation:'מדריך המשימה המאושר נוצר בנפרד מהתשובה של ה־AI, ולכן השוואה אליו היא אימות אמיתי — לא רק בדיקה שהתשובה נראית נכונה. עיצוב רשמי או ביטחון בניסוח אינם הוכחה.', criteria:criteria('אימות'), estimatedSeconds:105, unlockPower:'verification' }),
  make({ battleId:'battle_21', order:21, regionId:'certainty_tower', title:'סודות רשת', villain:'ד״ר ודאות', battleType:'fault_scan', skillLabel:'פרטיות', story:'מגן הפרטיות עצר פרטים שאינם נחוצים לברכה.', objective:'נקו את הטיוטה בלי למחוק הקשר שימושי.', instruction:'בחרו את שני הפרטים שיש להסיר.', concept:'לפני שיתוף עם AI, מסירים מידע אישי שאינו נחוץ.', choices:[{id:'name',label:'[שם מלא]'},{id:'address',label:'[כתובת בית]'},{id:'team',label:'צוות החילוץ',outcome:'זהו ההקשר הדרוש לברכה — הוא נשאר, כי הוא לא מזהה אדם ספציפי.'},{id:'length',label:'שני משפטים',outcome:'זהו אילוץ שימושי, לא מידע אישי — הוא נשאר בטיוטה.'}], correctChoiceIds:['name','address'], successMessage:'הברכה נשארה שימושית — בלי פרטים מזהים.', partialMessage:'חפשו פרטים שמזהים אדם ואינם נחוצים למשימה.', successExplanation:'שם מלא וכתובת בית מזהים אדם ואינם נחוצים לברכה לצוות החילוץ, ולכן הם הפרטים שיש להסיר. פרטיות אומרת לבדוק אילו פרטים מזהים אדם אמיתי ולהוציא אותם אם אינם הכרחיים למשימה.', criteria:['הסרת שם','הסרת כתובת','שמירת הקשר','הסבר פרטיות'], estimatedSeconds:105, unlockPower:'privacy' }),
  make({ battleId:'battle_22', order:22, regionId:'certainty_tower', title:'שומר הסף', villain:'ד״ר ודאות', battleType:'combo', skillLabel:'אחריות', story:'דוח המשימה כולל הצעה לא מאומתת ופרט אישי.', objective:'נקו ואמתו את הדוח לפני האישור.', instruction:'שמרו מידע נתמך והסירו את השאר.', concept:'תוצר AI הוא הצעה לבדיקה, לא הוכחה.', choices:[{id:'keep_scan',label:'שמרו: סריקת אזור'},{id:'remove_lasers',label:'הסירו: מופע לייזרים'},{id:'remove_phone',label:'הסירו: [מספר טלפון]'},{id:'remove_scan',label:'הסירו גם את סריקת האזור',outcome:'סריקת האזור דווקא נתמכת בנוהל. אימות דורש בדיקה מול המקור, לא הסרה אוטומטית.'},{id:'keep_all',label:'השאירו הכול כי זה כתוב בביטחון',outcome:'ניסוח בטוח אינו הוכחה. עדיין לא בוצע אימות של הטענה.'}], correctChoiceIds:['keep_scan','remove_lasers','remove_phone'], successMessage:'נשאר רק מידע מאומת ולא אישי.', partialMessage:'פרטיות קודמת; אחריה בודקים כל טענה מול המקור.', successExplanation:'שמירת סריקת האזור (נתמכת בנוהל), הסרת הצעת הלייזרים (לא מאומתת) והסרת מספר הטלפון (פרטי) — משקפות שתוצר AI הוא הצעה לבדיקה, לא אמת מוחלטת. קודם בודקים פרטיות, ואחר כך מאמתים כל טענה מול מקור נפרד.', criteria:['פרטיות','אימות','הבנת הסתברות','בדיקה מחדש'], estimatedSeconds:135, workshopVisit:4, unlockPower:'responsibility' }),
  make({ battleId:'battle_23', order:23, regionId:'finale', title:'שחזור התכנית', villain:'המשבש', battleType:'combo', skillLabel:'שילוב מלא', story:'המשבש מחק את לוח הבקרה. שחזרו אותו בעזרת המדריך.', objective:'כתבו ללופּ בקשה בטוחה ומלאה.', instruction:'כתבו בקשה שמשחזרת את התכנית.', concept:'מטרה, הקשר, אילוץ, פורמט ובדיקה יוצרים תהליך אחראי.', choices:[], correctChoiceIds:[], successMessage:'לוח התכנית שוחזר בהצלחה!', partialMessage:'תקנו רק את הרכיב שסומן ושמרו את השאר.', successExplanation:'מטרה, אילוץ, פורמט ובדיקת הצלחה — כשכולם מופיעים יחד, לופּ יודע בדיוק מה לבנות, כמה, איך להציג וכיצד לוודא שהתוצאה נכונה. זו השיטה המלאה לבקש דבר מורכב מ־AI ולבדוק את התוצאה בעצמכם.', criteria:['התאמה למשימה','רכיבי פרומפט','בדיקה ושיפור','אחריות ובטיחות'], estimatedSeconds:165 }),
];

export const battleById = Object.fromEntries(battles.map((battle) => [battle.battleId, battle])) as Record<string, BattleDefinition>;

// Typed distinction between a tutorial/training battle (no antagonist — the
// child is learning the simulator itself) and a villain battle. Driven by
// `battle.villain === null`, the same typed field battle content already
// sets per-battle — never inferred from displayed title/story text.
export function isTrainingBattle(battle: BattleDefinition): boolean {
  return battle.villain === null;
}

export interface SkillCatalogEntry { powerId: string; label: string; battleOrder: number }
export const skillCatalog: SkillCatalogEntry[] = battles
  .filter((battle): battle is BattleDefinition & { unlockPower: string } => Boolean(battle.unlockPower))
  .map((battle) => ({ powerId: battle.unlockPower, label: battle.skillLabel, battleOrder: battle.order }));

export function validateBattleRegistry(registry = battles): string[] {
  const errors: string[] = [];
  if (registry.length !== 23) errors.push('ה־registry חייב להכיל בדיוק 23 קרבות');
  registry.forEach((battle, index) => {
    if (battle.order !== index + 1) errors.push(`סדר לא תקין בקרב ${battle.battleId}`);
    if (battle.criteria.length !== 4) errors.push(`חסרים ארבעה קריטריונים בקרב ${battle.battleId}`);
    if (!battle.successExplanation.trim()) errors.push(`חסר הסבר הצלחה בקרב ${battle.battleId}`);
    if (battle.order < 23 && battle.correctChoiceIds.length === 0) errors.push(`אין פתרון לקרב ${battle.battleId}`);
  });
  if (new Set(registry.map((battle) => battle.battleId)).size !== registry.length) errors.push('מזהה קרב כפול');
  return errors;
}
